name: hello-world

on: push

jobs:
  get-gh-token:
    runs-on: ubuntu-latest

    outputs:
      access-token-gh: ${{ env.access_token }}

    steps:
      - name: Retrieve Github access token
        run: | 
          accessToken="testovatko"
          echo "$accessToken"
          echo "access_token=$accessToken" >> $GITHUB_ENV

  backup:
    name: Backup
    runs-on: ubuntu-latest
    needs: get-gh-token
    env:
      variable: ${{ needs.get-gh-token.outputs.access-token-gh }}

    steps:
      - name: Backing up Github repository 
        run: |
          echo ${{ needs.get-gh-token.outputs.access-token-gh }}
          echo "======="
          echo $variable