name: hello-world

on: push

jobs:
  hello-world-job:
    runs-on: windows-latest

    outputs:
      vystup: ${{ env.token }}

    steps:
      - name: Generate token
        shell: pwsh
        run: | 
          $tokeniste="hahahahaha"
          echo "$tokeniste v powershellu"
          echo "tokenek=$tokeniste" >> $GITHUB_ENV

      - name: Set variable with token
        shell: bash
        run: |
          echo "${{ env.tokenek }} v bashi"
          echo "token=${{ env.tokenek }}" >> $GITHUB_ENV

  goodbye-world-job:
    runs-on: ubuntu-latest

    needs: hello-world-job

    env:
      variable: ${{ needs.hello-world-job.outputs.vystup }}

    steps:
      - name: test variable passing
        shell: bash
        run: | 
          echo $variable