name: hello-world

on: push

jobs:
  get-gh-token:
    runs-on: windows-latest

    outputs:
      access-token-gh: ${{ env.access_token }}

    steps:
      - name: Retrieve Github access token
        shell: pwsh
        run: | 
          $accessToken="testovatko"
          echo "$accessToken"
          echo "access_token=$accessToken" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Output Github access token
        shell: pwsh
        run: |
          echo "Toto je ${{ access_token }}"

  backup:
    name: Backup
    runs-on: ubuntu-latest
    needs: get-gh-token
    env:
      variable: ${{ needs.get-gh-token.outputs.access-token-gh }}

    steps:
      - name: Backing up Github repository 
        shell: bash
        run: |
          echo $variable