name: hello-world

on:
  pull_request:
    branches:
      - 'main'

jobs:
  get-gh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Get URL of the run
        id: get-url
        uses: havlicek-oksystem/eksn/.github/actions/get-run-name@main

      - name: Output run URL
        shell: bash
        if: github.event_name == 'pull_request'
        run: | 
          echo "Toto je pull request"