name: hello-world

on: push

jobs:
  hello-world-job:

    runs-on: ubuntu-latest
    outputs:
      vystup: ${{ steps.token_gen.outputs.token }}
    steps:
      
      - name: Generate token
        id: token_gen
        run: | 
          token="hahahahaha"
          echo "$token"
          echo "token=$token" >> GITHUB_OUTPUT

  goodbye-world-job:

    runs-on: ubuntu-latest
    needs: hello-world-job
    env:
      variable: ${{ needs.hello-world-job.outputs.vystup }}
    steps:
      - name: test variable passing
        run: | 
          echo $variable