name: hello-world

on:
  push:
    branches:
      - 'workflow-test'


jobs:
  test-semver:
    runs-on: ubuntu-latest

    steps:
      - name: test
        shell: bash
        run: |
          echo "Toto bylo spusteno z branche."