name: hello-world

on: push

jobs:
  get-gh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve Github access token
        id: token
        shell: bash
        run: | 
          pole=("blbost1" "blbost2" "blbost3")
          echo "array=${pole[@]}" >> $GITHUB_OUTPUT

      - name: Output Github access token
        shell: bash
        run: |
          echo ${{ steps.token.outputs.array }}