name: hello-world

on: push

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: check out repository code
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: | 
          echo "$(cat hello_world.txt)"
          pwd