name: hello-world

on:
  push:
    branches:
      - 'main'


jobs:
  test-semver:
    runs-on: ubuntu-latest

    steps:
      - name: Install java
        uses: ./.github/actions/setup_java
        with:
          JAVA_VERSION: "21"
          JAVA_DISTRIBUTION: "corretto"