name: hello-world

on:
  workflow_dispatch:
    inputs:
      input:
        type: choice
        options:
        - success
        - fail

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        id: test
        shell: bash
        run: |
          echo "var1=cement" >> $GITHUB_OUTPUT

      - name: Test2
        env:
          variable: ${{ steps.test.outputs.var1 == 'cement' || 'pisek' }}
        shell: bash
        run: |
          echo "Stavi se z: ${{ env.variable }}"
