name: hello-world

on:
  workflow_dispatch:
    inputs:
      branch: 'main'

jobs:
  test-semver:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }} && github.ref == 'refs/heads/main'
        with:
          java-version: "21"
          distribution: "corretto"