name: hello-world

on:
  push:
    branches:
      - 'main'
      - 'release/**'

    tags:
      - 'release/**'


jobs:
  test-semver:
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Install NPM
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install SemVer
        shell: bash
        run: |
          npx semantic-release