name: hello-world

on: push

jobs:
  get-gh-token:
    runs-on: windows-latest

    outputs:
      access-token-gh: $${{ env.access_token }}

    steps:
      - name: Retrieve Github access token
        shell: pwsh
        run: | 
          $accessToken="testovatko"
          echo "$accessToken"
          echo "access_token=$accessToken" >> $GITHUB_ENV

  backup:
    name: Backup
    runs-on: windows-latest
    needs: get-gh-token
    env:
      variable: ${{ needs.get-gh-token.outputs.access-token-gh }}

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          
      - name: Backing up Github repository 
        shell: pwsh
        run: |
          echo ${{ needs.get-gh-token.outputs.access-token-gh }}
          echo "======="
          echo $variable