name: hello-world

on:
  workflow_dispatch:
    inputs:
      input:
        type: choice
        options:
        - success
        - fail

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        id: test
        shell: bash
        run: |
          echo "var1=hlina" >> $GITHUB_OUTPUT

      - name: Test2
        shell: bash
        continue-on-error: ${{ steps.test.outputs.var1 == 'cement' }}
        run: |
          curl kravina
          echo "TENTO STEP PROBIHA"
