name: hello-world

on:
  workflow_dispatch:

jobs:
  get-gh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Get URL of the run
        id: get-url
        uses: havlicek-oksystem/eksn/.github/actions/get-run-name@main
