name: hello-world

on: push

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: check out repository code
        if: ${{ ('success' == 'success' || 'success' == 'cancelled') && contains('integration,release', 'integration') }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: | 
          echo "$(cat hello_world.txt)"
          pwd