name: PR verification GitLeaks

on:
  pull_request:
    types: 'opened'
    branches:
      - 'main'

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Gitleaks Scan
        shell: bash
        run: |
          echo "Gitleaks result:" >> $GITHUB_STEP_SUMMARY
          echo "Nalezeleno nula secrets leaks." >> $GITHUB_STEP_SUMMARY
          echo "Tento komantar byl vytvoren automaticky v ramci Gitleaks scanu na PR." >> $GITHUB_STEP_SUMMARY
          echo "========"
          echo $GITHUB_STEP_SUMMARY

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.KLICEK }}
          script: |
            echo "Zkouska bashe z github-scriptu"
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Tento komentar byl vytvoren automaticky v ramci testu komentovani na PR.'
            })