name: PR verification GitLeaks

on:
  pull_request:
    branches:
      - 'main'

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest
    permissions: 
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.KLICEK }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Tento komentar byl vytvoren automaticky v ramci testu komentovani na PR.'
            })

      - name: Output event
        shell: bash
        run: |
          echo "Tento run byl spusteny pomoci pull requestu a tudiz ho ukoncuji s neuspechem"
          exit 1
