name: PR verification GitLeaks

on:
  pull_request:
    types: opened
    branches:
      - 'main'

  issue_comment:
    types: 'created'
    branches:
      - 'main'

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        id: branch
        shell: bash
        run: |
          branch=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.KLICEK }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/havlicek-oksystem/eksn/pulls/${{ github.event.pull_request.number }} | jq -r '.head.ref')
          echo "Branch je $branch"
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git checkout $branch

      - name: Download GitLeaks
        shell: bash
        run: |
          gitleaksURL=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep "browser_download_url.*linux_x64" | cut -d : -f 2,3 | tr -d \")
          curl -L $gitleaksURL | tar xz

      - name: Scan
        id: scan
        shell: bash
        run: |
          cd repo
          ../gitleaks git . -v --log-opts="$(git remote show origin | sed -n '/HEAD branch/s/.*: //p').." --exit-code 0 > gitleaks.log
          if [ $(cat gitleaks.log | wc -l) -ne 0 ]; then
            commentBody="### Gitleaks scan ⛔ ###\nGitleaks scan našel v pull requestu následující secrets:\n"
            grep "File: " gitleaks.log | awk '{print $2}' > gitleaks.files
            grep "Line: " gitleaks.log | awk '{print $2}' > gitleaks.lines
            trap $(grep "Email: " gitleaks.log | awk '{print $2}' > gitleaks.emails) EXIT
            trap $(grep "Commit: " gitleaks.log | awk '{print $2}' > gitleaks.commits) EXIT
          else
            commentBody="### Gitleaks scan ✅ ###\nGitleaks scan nenašel v pull requestu žádné secrets.\n"
            touch gitleaks.files gitleaks.lines gitleaks.emails gitleaks.commits
          fi

          for (( i=1; i < $(cat gitleaks.files | wc -l)+1; i++))
          do
            commentBody+=$(echo "$(sed -n ${i}p gitleaks.files), line $(sed -n ${i}p gitleaks.lines): \
            $(sed -n ${i}p gitleaks.emails) $(sed -n ${i}p gitleaks.commits)")
          done

          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.KLICEK }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/havlicek-oksystem/eksn/issues/${{ github.event.pull_request.number }}/comments -d '{"body":"'"$commentBody"'"}'

          if [ $(cat gitleaks.log | wc -l) -eq 0 ]; then
            exit 0
          else
            exit 1
          fi